const bgMusic=document.getElementById('bgMusic'),musicToggle=document.getElementById('musicToggle'),musicIcon=document.getElementById('musicIcon'),entranceScreen=document.getElementById('entranceScreen'),enterBtn=document.getElementById('enterBtn');let musicPlaying=!1;
function setPlaying(){musicPlaying=!0,musicToggle.classList.add('playing'),musicIcon.innerHTML='\u266B'}
function setPaused(){musicPlaying=!1,musicToggle.classList.remove('playing'),musicIcon.innerHTML='\u266A'}
enterBtn.addEventListener('click',function(){bgMusic.play().then(setPlaying).catch(function(){}),entranceScreen.classList.add('hidden'),setTimeout(function(){entranceScreen.style.display='none'},1200)});
musicToggle.addEventListener('click',function(e){e.stopPropagation(),musicPlaying?(bgMusic.pause(),setPaused()):bgMusic.play().then(setPlaying).catch(function(){})});
const menuToggle=document.getElementById('menuToggle'),mobileMenu=document.getElementById('mobileMenu'),menuOverlay=document.getElementById('menuOverlay');
function closeMenu(){menuToggle.classList.remove('active'),mobileMenu.classList.remove('open'),menuOverlay.classList.remove('show')}
menuToggle.addEventListener('click',function(){menuToggle.classList.toggle('active'),mobileMenu.classList.toggle('open'),menuOverlay.classList.toggle('show')}),menuOverlay.addEventListener('click',closeMenu);
function navigate(t){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page')),document.getElementById(t).classList.add('active-page'),window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-links a, .mobile-menu a').forEach(l=>{l.addEventListener('click',function(){navigate(this.dataset.target),closeMenu()})}),document.getElementById('logoHome').addEventListener('click',function(){navigate('landing'),closeMenu()}),document.querySelectorAll('.action-btn').forEach(b=>{b.addEventListener('click',function(){navigate(this.dataset.target)})}),document.querySelectorAll('.luxury-square').forEach(s=>{s.addEventListener('click',function(){navigate(this.dataset.target)})});
const GS_URL='https://script.google.com/macros/s/AKfycbw0w18vI0MUpDJS3xvRTFJzVoFsZOLnu8Sw1JUCKo6i0AXgfQgI4g10XxeNP9VJpllq3g/exec';
document.getElementById('weddingRsvpForm').addEventListener('submit',function(e){e.preventDefault();var s=document.getElementById('submitBtn');s.disabled=!0,s.textContent='Sending...';var d={name:document.getElementById('guest-name').value,email:document.getElementById('guest-email').value||'N/A',attendance:document.querySelector('input[name="attendance"]:checked').value,dietary:document.getElementById('dietary').value};fetch(GS_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(){document.getElementById('weddingRsvpForm').reset(),s.disabled=!1,s.textContent='Submit RSVP',navigate('thankyou')}).catch(function(){document.getElementById('weddingRsvpForm').reset(),s.disabled=!1,s.textContent='Submit RSVP',navigate('thankyou')}),setTimeout(function(){document.getElementById('thankyou').classList.contains('active-page')||(document.getElementById('weddingRsvpForm').reset(),s.disabled=!1,s.textContent='Submit RSVP',navigate('thankyou'))},3e3)});
const wd=new Date('2027-02-21T16:00:00').getTime();function updateCountdown(){const n=new Date().getTime(),d=wd-n;if(d<0)return void(document.getElementById('countdown').innerHTML='<p>The big day is here!</p>');document.getElementById('days').textContent=String(Math.floor(d/864e5)).padStart(2,'0'),document.getElementById('hours').textContent=String(Math.floor(d%864e5/36e5)).padStart(2,'0'),document.getElementById('minutes').textContent=String(Math.floor(d%36e5/6e4)).padStart(2,'0'),document.getElementById('seconds').textContent=String(Math.floor(d%6e4/1e3)).padStart(2,'0')}updateCountdown(),setInterval(updateCountdown,1e3);
document.querySelectorAll('.gallery-img').forEach(i=>{i.addEventListener('click',function(){window.open(this.src,'_blank')})});
const hv=document.querySelector('.hero-video');hv&&hv.play().catch(function(){});